### ISSUE TITLE
Allow unmounting devices by /dev/disk/by-id/XXXXXXXXXXXXXX symlinks on GNU/Linux

### ISSUE THREAD

**Issue by jviotti** [balena-io-modules/mountutils#18]

**Comment by lurch** [comment]
There's actually a whole bunch of directories in `/dev/disk/` :
```
by-id
by-label
by-partlabel
by-partuuid
by-uuid
```
In each case each of the files in those dirs is a symlink to the real device-node, so it should just be a case of switching from `stat` to `lstat`, seeing if you got a `S_ISLNK`, calling `readlink`,  and then using `realpath` to resolve the readlink result if it didn't start with a `/`. Simples ;-)

**Comment by jviotti** [comment]
Closing stale issues
